USE [master]
GO

/****** Object:  Database [blog]    Script Date: 11/07/2018 20:19:18 ******/
CREATE DATABASE [blog]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'blog', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\blog.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'blog_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\blog_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [blog] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [blog].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [blog] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [blog] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [blog] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [blog] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [blog] SET ARITHABORT OFF 
GO

ALTER DATABASE [blog] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [blog] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [blog] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [blog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [blog] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [blog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [blog] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [blog] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [blog] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [blog] SET  DISABLE_BROKER 
GO

ALTER DATABASE [blog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [blog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [blog] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [blog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [blog] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [blog] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [blog] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [blog] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [blog] SET  MULTI_USER 
GO

ALTER DATABASE [blog] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [blog] SET DB_CHAINING OFF 
GO

ALTER DATABASE [blog] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [blog] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [blog] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [blog] SET QUERY_STORE = OFF
GO

USE [blog]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [blog] SET  READ_WRITE 
GO

